version: "3.8"
services:
  ohc-profiles-bot:
    build: .
    container_name: ohc-profiles-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - LEADERBOARD_CHANNEL_ID=${LEADERBOARD_CHANNEL_ID}
      - LEADERBOARD_CRON=${LEADERBOARD_CRON}
      - NODE_ENV=production
    volumes:
      - ./:/app
    restart: unless-stopped
