name: Build & Publish Docker (ohc-profiles-bot)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ohc-profiles-bot

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # -------------------------
      # Export tarballs for Synology import
      # -------------------------

      - name: Build ARM64 tar (Synology aarch64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ohc-profiles-bot:arm64 \
            -o type=docker,dest=ohc-profiles-bot-arm64.tar \
            .

      - name: Upload ARM64 tar
        uses: actions/upload-artifact@v4
        with:
          name: ohc-profiles-bot-arm64
          path: ohc-profiles-bot-arm64.tar

      - name: Build AMD64 tar (Synology x86_64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ohc-profiles-bot:amd64 \
            -o type=docker,dest=ohc-profiles-bot-amd64.tar \
            .

      - name: Upload AMD64 tar
        uses: actions/upload-artifact@v4
        with:
          name: ohc-profiles-bot-amd64
          path: ohc-profiles-bot-amd64.tar
